global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'h3x-frontend'
    static_configs:
      - targets: ['h3x-frontend:3000']
    scrape_interval: 30s
    metrics_path: '/metrics'

  - job_name: 'h3x-backend'
    static_configs:
      - targets: ['h3x-backend:3007']
    scrape_interval: 30s
    metrics_path: '/api/metrics'

  - job_name: 'h3x-websocket'
    static_configs:
      - targets: ['h3x-websocket:3008']
    scrape_interval: 30s
    metrics_path: '/metrics'

  - job_name: 'mongodb'
    static_configs:
      - targets: ['mongodb:27017']
    scrape_interval: 30s

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s

  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:80']
    scrape_interval: 30s
