name: Automated Maintenance

on:
  schedule:
    - cron: '0 3 * * 0' # Weekly on Sunday at 3 AM
  workflow_dispatch: # Allow manual triggering

jobs:
  maintenance:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Automatically fix formatting issues
        run: npm run format
      
      - name: Automatically fix linting issues
        run: npm run lint
      
      - name: Check for unused dependencies
        run: |
          echo "## Unused Dependencies Report" > maintenance-report.md
          echo "Generated on: $(date)" >> maintenance-report.md
          echo "" >> maintenance-report.md
          npx depcheck --json >> depcheck-results.json || true
          if [ -s depcheck-results.json ]; then
            echo "### Unused Dependencies Found:" >> maintenance-report.md
            cat depcheck-results.json >> maintenance-report.md
          else
            echo "No unused dependencies found." >> maintenance-report.md
          fi
      
      - name: Run security audit
        run: |
          echo "" >> maintenance-report.md
          echo "## Security Audit Results" >> maintenance-report.md
          npm audit --json >> audit-results.json || true
          if [ -s audit-results.json ]; then
            echo "### Security vulnerabilities found:" >> maintenance-report.md
            echo '```json' >> maintenance-report.md
            cat audit-results.json >> maintenance-report.md
            echo '```' >> maintenance-report.md
          else
            echo "No security vulnerabilities found." >> maintenance-report.md
          fi
      
      - name: Run code quality checks
        run: |
          echo "" >> maintenance-report.md
          echo "## Code Quality Check Results" >> maintenance-report.md
          npm run test:all || echo "Some tests failed - review needed" >> maintenance-report.md
      
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: automated maintenance and cleanup"
          title: "🤖 Automated Weekly Maintenance"
          body: |
            This PR contains automated maintenance tasks:
            
            - Code formatting fixes (Prettier)
            - Linting fixes (ESLint)
            - Dependency audit and unused dependency detection
            - Security vulnerability scan
            - Code quality checks
            - Automated cleanup suggestions
            
            Please review the maintenance report and merge if everything looks good.
            
            **Generated by:** GitHub Actions Automated Maintenance
          branch: automated/maintenance-${{ github.run_number }}
          labels: |
            automated
            maintenance
            review-required
          draft: false
